### ISSUE TITLE
Glowing-home-page(Dark theme)

### ISSUE THREAD

**Issue by Arshdeep-13** [CommunityPro/portfolio-html#137]
## Website design appears too simplistic
As a visitor, when I visit the website, I find the design to be too simplistic. While it is good, I believe it can be improved to enhance the user experience.

## Solution
I have made updates to your website by incorporating a captivating glowing effect in the dark theme, which adds an amazing visual element. This enhancement aims to elevate the overall user experience.

## Additional context
For additional screenshots and detailed code changes, please refer to my pull request: 
`https://github.com/CommunityPro/portfolio-html/pull/136`

I kindly request you to review and consider merging this pull request. Thank you for your time.

Best regards,
@Arshdeep-13

**Comment by Evavic44** [comment]
Thanks for raising this issue, @Arshdeep-13. I don't think I was clear with my comment on your previous PR. The simplicity of the portfolio is actually deliberate since it is a simple template, we want to give users the liberty to customize it however they desire. 

This is why this issue sadly isn't required for now. Feel free to customize it as your own portfolio and add it to the list of examples [here](https://github.com/CommunityPro/portfolio-html#examples). 

I'll be closing this issue for now. Thanks.

**Comment by Arshdeep-13** [comment]
Ok sir
I will add it in the examples section as it took my lot of effort and time.
