### ISSUE TITLE
Site not loading

### ISSUE THREAD

**Issue by Benrobo** [CommunityPro/portfolio-html#48]
After going through the site url present in the repo, nothing loads except from the navbar, also the links doesn't do anything when clicked.
Don't know if this a feature or a bug?

**Comment by winniffy** [comment]
hi @Benrobo, i think the code is being written in bits in order to match everyone's pace - especially beginners -, therefore it is intentional.

**Comment by Evavic44** [comment]
> After going through the site url present in the repo, nothing loads except from the navbar, also the links doesn't do anything when clicked. Don't know if this a feature or a bug?

Thanks for raising an issue in the community @Benrobo 🙌🏾 As @winniffy said, we are building the project as a community, gradually improving with each iteration. The empty links are actually deliberate 😅 because this is a template project, so they will be filled by the one using it. 

Hope this answers your question?

**Comment by Benrobo** [comment]
ok, if you say so.
